---
title: "Using MBatch Corrections: EB_withNonParametricPriors"
author: "Tod Casasent"
date: "`r Sys.Date()`"
#output: rmarkdown::html_vignette
# install with vignettes using devtools::install(build_vignettes = TRUE)
# build vignettes using devtools::build_vignettes() (inst/doc)
output: 
  pdf_document:
    number_sections: TRUE
vignette: >
  %\VignetteIndexEntry{Using MBatch Corrections: EB_withNonParametricPriors}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

These instructions are aimed at people familiar with R and familiar with TCGA/GDC platforms and data types. They are intended to introduce the reader to producing the given assessment. These instructions will only rarely, if ever, touch on the appropriateness of the assessment algorithm or interpretation of output. See MBatch_01_InstallLinux for instructions on downloading test data.

# Algorithm

EB with non-Parametric Priors performs Empirical Bayes correction taking a BEA_DATA object (with data matrix and batch dataframe) and returning either a corrected matrix or a string containing the path to where the data file was written.

# Output

The primary output method for MBatch is to view results in the Batch Effects Website. Correction algorithms generally do not create graphical output and instead create TSV output files.

# Usage

EB_withNonParametricPriors(theBeaData, theBatchIdsNotToCorrect,
theDoCheckPlotsFlag, theBatchType, theThreads = 1, thePath = NULL,
theWriteToFile = FALSE)

# Arguments

## theBeaData

BEA_DATA objects can be created by calls of the form new("BEA_DATA", theData, theBatches, theCovariates). If you have no covariate data, use an empty data.frame created with data.frame()

mData:
Object of class "matrix" A matrix where the colnames are sample ids and the rownames are gene equivalents. All names should be strings, not factors.

mBatches:
Object of class "data.frame" A data.frame where the column "names" are batch types. The first batch "type" is "Sample". All names and values should be strings, not factors or numeric.

mCovariates:
Object of class "data.frame" A data.frame where the column "names" are covariate types. The first covariate "type" is "Sample". All names and values should be strings, not factors or numeric.

## theBatchIdsNotToCorrect
A vector of strings giving batch names/ids within the batch type that should not be corrected

## theDoCheckPlotsFlag
Defaults to FALSE. TRUE indicates a prior plots image should be created.

## theBatchType
A string identifying the batch type to correct.

## theThreads
Integer defaulting to 1. Number of threads to use for calculating priors.

## thePath
Output path for any files.

## theWriteToFile
TRUE to write the corrected data to file and return the file pathname instead of the corrected matrix.

# Example Call

The following code is adapted from the tests/EB_withNonParametricPriors.R file. Data used is from the testing data as per the MBatch_01_InstallLinux document. In the future, we plan to make the output from MBatch more user friendly, but currently, this produces the following output at the command line.

```{r, echo=TRUE}
{
  library(MBatch)
  
  # set the paths
  invariantFile="/bea_testing/MATRIX_DATA/rbn-pseudo-iset.tsv"
  variantFile="/bea_testing/MATRIX_DATA/rbn-pseudo-vset.tsv"
  theOutputDir="/bea_testing/output/RBN_Pseudoreplicates"
  theRandomSeed=314
  
  theGeneFile="/bea_testing/MATRIX_DATA/matrix_data-Tumor.tsv"
  theBatchFile="/bea_testing/MATRIX_DATA/batches-Tumor.tsv"
  theOutputDir="/bea_testing/output/EB_withNonParametricPriors"
  theRandomSeed=314
  theBatchType="TSS"
  
  # make sure the output dir exists and is empty
  unlink(theOutputDir, recursive=TRUE)
  dir.create(theOutputDir, showWarnings=FALSE, recursive=TRUE)
  # load data
  myData <- mbatchLoadFiles(theGeneFile, theBatchFile)
  myData@mData <- mbatchTrimData(myData@mData, 100000)
  # call
  outputFile <- EB_withNonParametricPriors(theBeaData=myData,
                             theBatchIdsNotToCorrect=c(""),
                             theDoCheckPlotsFlag=TRUE,
                             theBatchType=theBatchType,
                             theThreads=1,
                             thePath=theOutputDir,
                             theWriteToFile=TRUE)
  correctedMatrix <- readAsGenericMatrix(outputFile)
  print(correctedMatrix[1:4, 1:4])
}
```

# Example File Output

The above code creates the following output file. File is named using the following naming convention:
ANY_Corrections-EBwithNonParametricPriors.tsv
The TSV file with the corrected dataset is written by the MBatch package. The end of the output shows a snippet from the corrected matrix.
