# this is the docker-compose version
version: '3.0'

# file version 2020-07-20-1100


services:
    mbatchsa_service:
        # use existing default network
        network_mode: bridge
        # restart this container if it crashes
        restart: always
        build:
            # build from directory in context and Dockerfile
            context: .
            dockerfile: Dockerfile
        container_name: mbatchsa_cont_extr
        # update :latest to desired version
        image: mdabcb/mbatchsa_image:latest
        volumes:
            # outside access for data files outside:inside
            - /MBatchSA/mbatch:/MBATCH
            - /MBatchSA/website:/WEBSITE
            # read-only file to set time and timezone to same in image as on server
            - /etc/localtime:/etc/localtime:ro
            - /etc/localtime:/etc/timezone:ro
        ports:
            # (outside)host port:container port(inside) for RStudio
            - "8080:8787"
        tty: true
